name: Java CI

on:
  push:
    branches: [ "DEV" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: WebService
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
         service-id: 
         api-key: 
