name: Java BRANCH PROD

on:
    pull_request:
      branches: [ "QA" ]

jobs:
  build:
  
      runs-on: ubuntu-latest

      steps:
          - name: Render Deploy Action
            uses: johnbeynon/render-deploy-action@v0.0.8
            with:
              service-id: ${{secrets.SERVICE_ID}}
              api-key: ${{secrets.API_KEY}}
